### ISSUE TITLE
Installing enscript on Cygwin

### ISSUE THREAD

**Issue by CMCDragonkai** [svenax/SublimePrint#15]
Can I pass the absolute path to enscript executable, my enscript is part of the Cygwin PATH which is not inside the Windows native PATH.

**Comment by svenax** [comment]
That requires you to use a slash as first character in the path somehow. I know that you can use `/c/some/path` in Cygwin instead of `c:\some\path`, but I'm not sure if you can use that outside the Cygwin shell.
