### ISSUE TITLE
Can't configure keyboard bindings

### ISSUE THREAD

**Issue by jhorneman** [svenax/SublimePrint#16]
It seems I cannot configure the SublimePrint's keyboard bindings. And given there's no print dialog and I've already printed out various documents by accident, I really, really need to be able to configure this.

I've looked in all the settings, I've configured Sublime keyboard bindings before, but I've not found a way to do this. I've tried modifying the sublime package and overriding the settings, with no results.

**Comment by svenax** [comment]
Sorry for the late reply. Just put this in your **Key Bindings - User** file and change as needed:
```
	{ "keys": ["ctrl+alt+p"], "command": "print_file"},
	{ "keys": ["ctrl+shift+alt+p"], "command": "print_selection"},
```
