### ISSUE TITLE
Windows 10 - lpstat not found

### ISSUE THREAD

**Issue by dazdaz** [svenax/SublimePrint#20]
Upon installation of this on Windows 10 with sublime3 build 3114, I receive the error lpstat not found when I try to print out a document.

Does lpstat.exe exist on Windows, is there an equivalent, can lpstat be used from a 3rd party which is compiled for Windows, is there a workaround.

**Comment by svenax** [comment]
You can maybe use the executable from MSYS or similar. But it is easier if you make the configuration yourself. See issue https://github.com/svenax/SublimePrint/issues/5 for ideas.

**Comment by dazdaz** [comment]
Why not just include a pre-compiled lpstat.exe with Sublime.

**Comment by svenax** [comment]
That seems to be a bit out of scope, since Sublime itself doesn't do any printing.
