### ISSUE TITLE
add quick start to readme

### ISSUE THREAD

**Issue by cod3licious** [svenax/SublimePrint#21]
Works like a charm but after installing I had no idea how to use it. Of course I quickly figured out that I could check the command palette if a new command was created for printing but it might be nice to add this hint (and maybe also the respective shortcuts for printing) to the readme/info that opens after installing the package.
Thanks! :)

**Comment by svenax** [comment]
Thanks. I have tweaked the info text a little to note that the printing commands are added to the File menu and to the editor view context menu.
