### ISSUE TITLE
How to install this in Sublime text

### ISSUE THREAD

**Issue by metalox** [svenax/SublimePrint#25]
Excuse the dumb question: I have installed Enscript OK. Now, how do I "install", if that is the right term, SublimePrint in Sublime Text 3 please? I have tried "Install Package" but SublimeText is not an option. I guess I am missing a step?

**Comment by svenax** [comment]
Assuming you have installed [Package Control](https://packagecontrol.io/installation) already, just search for **Simple Print Function** in the installable packages.

**Comment by metalox** [comment]
Thank you. I swear I did that and didn't find anything! It works now. Thank you for taking the time to reply.
