### ISSUE TITLE
Command 'enscript' not found on Win7

### ISSUE THREAD

**Issue by dpneumo** [svenax/SublimePrint#5]
Using ST3 on a virtualized Win7 Pro.

Have carefully installed enscript from http://gnuwin32.sourceforge.net/packages/enscript.htm. (Used the zipped binaries). Checked the presence of enscript.exe and accompanying files in the bin folder. Set PATH to include the bin folder where enscript was installed. 

SublimePrint was installed via Package Control. Verified the presence of 'Simple Print Function.sublime-package' in <user>/AppData/Roaming/Sublime Text 3/Installed Packages. Restarted everything. 

Receive error: "Command 'enscript' not found! Please review the documentation." when I attempt to print.

Am not a python programmer but review of the code in SublimePrint.py suggests that find_command only searches the paths in the BIN_PATHS array and issues the error shown above if enscript.exe is not found in those paths. It does not appear that setting windows PATH has any effect.

I think the fix would involve parsing windows PATH for the paths to try and then appending those to BIN_PATHS. Alternatively appropriate paths could be hard coded into BIN_PATHS but that seems rather inflexible.

I appreciate the work you have done to develop this. Hope this observation is helpful.

**Comment by mikeyww** [comment]
[Another solution](https://forum.sublimetext.com/t/printing-from-sublime/281/144).
