### ISSUE TITLE
Using Virtual_PDF_Printer

### ISSUE THREAD

**Issue by renodesper** [svenax/SublimePrint#7]
I have Virtual_PDF_Printer for printing into pdf file. I already change "used_printer" parameter into it. Cups says that the job is already completed but I can't find the printed text. Where should SublimePrint generate it's output? Or is it support printing to pdf file already?

**Comment by svenax** [comment]
I have no idea. That probably depends on the printer driver. Maybe it supports setting a default location for the output files.
